web:
  build: .
  ports:
    - "80:80"
    - "5000:5000"
    - "5001:5001"
    - "9999:9999"
  volumes:
    - .:/code
  links:
    - redis
    - postgres
  environment:
    - POSTGRES_HOST=postgres

redis:
  image: redis

postgres:
  image: postgres
