"""empty message

Revision ID: 1359abcd626
Revises: 238d415f0bc
Create Date: 2015-06-20 16:09:29.014072

"""

# revision identifiers, used by Alembic.
revision = '1359abcd626'
down_revision = '238d415f0bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('admin', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('app_user', sa.Column('info_update', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'info_update')
    op.drop_column('app_user', 'admin')
    ### end Alembic commands ###
