"""empty message

Revision ID: 238d415f0bc
Revises: 1842253aadb
Create Date: 2015-06-20 15:51:04.406245

"""

# revision identifiers, used by Alembic.
revision = '238d415f0bc'
down_revision = '1842253aadb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('alliance_id', sa.Integer(), nullable=True))
    op.add_column('app_user', sa.Column('alliance_name', sa.String(), nullable=True))
    op.add_column('app_user', sa.Column('corp_id', sa.Integer(), nullable=True))
    op.add_column('app_user', sa.Column('corp_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'corp_name')
    op.drop_column('app_user', 'corp_id')
    op.drop_column('app_user', 'alliance_name')
    op.drop_column('app_user', 'alliance_id')
    ### end Alembic commands ###
