"""empty message

Revision ID: 2b4e7605173
Revises: None
Create Date: 2015-06-06 08:56:16.108347

"""

# revision identifiers, used by Alembic.
revision = '2b4e7605173'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prx_user',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('provider_id', sa.Integer(), nullable=False),
                    sa.Column('provider_name', sa.String(), nullable=False),
                    sa.Column('character_id', sa.Integer(), nullable=False),
                    sa.Column('character_name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('last_login', sa.DateTime(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('character_id')
                    )
    op.create_index('provider', 'prx_user', ['provider_id', 'provider_name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('provider', table_name='prx_user')
    op.drop_table('prx_user')
    ### end Alembic commands ###
