"""todo

Revision ID: a4dea3eba1
Revises: 2b4e7605173
Create Date: 2015-06-06 14:22:34.618567

"""

# revision identifiers, used by Alembic.
revision = 'a4dea3eba1'
down_revision = '2b4e7605173'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prx_todo',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('creator_id', postgresql.UUID(), nullable=False),
                    sa.Column('task', sa.String(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], ['prx_user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prx_todo')
    ### end Alembic commands ###
